### ISSUE TITLE
Errors on building

### ISSUE THREAD

**Issue by tajnymag** [DanielHuisman/node-wii#1]
I'm trying to use your module for my home project and I got in trouble while trying to build/install it.

make calls out errors in the source code. Specifically in wiimote.h. First error is on line 29. 

I'm trying to build it in a clean environment on freshly installed Ubuntu Server.

[Here's the generated npm-debug.log](https://github.com/DanielHuisman/node-wii/files/908233/npm-debug.txt)

**Comment by Wqrld** [comment]
same problem here on raspian jessie lite, have you found a fix?

**Comment by tajnymag** [comment]
@aycgit Unfortunately I haven't. I had to use python + cwiid.

**Comment by Wqrld** [comment]
i wanted to use node because python isnt async but i guess i will need to use python then

**Comment by Wqrld** [comment]
@DanielHuisman you should also have a package.json but this seems to be a problem in cwiid, which cwiid version should we use?

Edit: zie dat je nl bent, kan je hier wat aan doen?

**Comment by DanielleHuisman** [comment]
I just tried running it myself and encountered the same problem. From what I can tell after some quick Googling is that there are some breaking changes in Node 0.11.x. Personally I haven't used the library since then, so that's why I never noticed it before. Basically the C++ code has to be updated to Node 6 or 7. I currently don't have time to look into it myself, but feel free to make a PR.

**Comment by Wqrld** [comment]
Ill just downgrade my node then, but if it's a easy fix which you just dont have time for ill do it.

**Comment by Wqrld** [comment]
@DanielHuisman downgrading node doesn't fix it, running sudo npm install wii on node 4.8.2 still results in the same problem

edit: some quick googling makes it look like you are including a class with #Include and not with class? i dont know c++ but can this be the problem?

edit 2: the problem seems to be somewhere around https://github.com/DanielHuisman/node-wii/blob/master/include/wiimote.h#L4

**Comment by DanielleHuisman** [comment]
Like I said, something changed way back in Node 0.11.x. So only downgrading to Node 0.10.x will fix the problem.
Some of the function argument signatures changed, for example on here: https://github.com/DanielHuisman/node-wii/blob/master/include/wiimote.h#L132.

The new signature looks something like this: https://github.com/nodejs/node-gyp/blob/master/test/node_modules/hello_world/hello.cc#L7

**Comment by Wqrld** [comment]
Okay, this goes far above what i understand, if you have some extra time you know what to do :)

**Comment by DanielleHuisman** [comment]
Closed in place of #2.
